GestionEvenements/Controllers/AdressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestionEvenements.Services.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionEvenements.Services.Dal;
using Microsoft.AspNetCore.Authorization;
using Modele;

namespace GestionEvenements.Controllers
{
    [Authorize]
    [TypeFilter(typeof(LogExceptionFilter))]
    public class AdressesController : Controller
    {
        private readonly RepoAdresses _repo;

        public AdressesController(RepoAdresses repo)
        {
            _repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _repo.Liste().ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adresse = await _repo.LireAsync(id.Value);
            if (adresse == null)
            {
                return NotFound();
            }

            return View(adresse);
        }

        // GET: Adresses/Create/EvenementId? avec nom du paramètre id prédéfini
        public async Task<IActionResult> Create(int? id)
        {
            if (id.HasValue)
            {
                Evenement evenement = null;
                var repo = new RepoEvenements(_repo.Context);

                evenement = await repo.LireAsync(id.Value);

                if (evenement == null)
                {
                    return NotFound();
                }

                ViewBag.EvenementId = evenement.EvenementId;
                ViewBag.TitreEvenement = evenement.Titre;
            }

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdresseId,Titre,Rue,CodePostal,Ville,Region,Pays,Notes,Latitude,Longitude")] Adresse adresse, int? id)
        {
            if (ModelState.IsValid)
            {
                await _repo.Creer(adresse);

                // Associer la nouvelle adresse à l'événement si on a son Id
                if (id.HasValue)
                {
                    var repo = new RepoEvenements(_repo.Context);

                    var evenement = await repo.LireAsync(id.Value);

                    if (evenement == null)
                    {
                        return NotFound();
                    }
                    evenement.AdresseId = adresse.AdresseId;
                    await repo.Modifier(evenement);
                    return RedirectToAction(nameof(Details), "Evenements", new { id = id.Value });
                }

                return RedirectToAction(nameof(Index));
            }
            return View(adresse);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adresse = await _repo.LireAsync(id.Value);
            if (adresse == null)
            {
                return NotFound();
            }
            return View(adresse);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdresseId,Titre,Rue,CodePostal,Ville,Region,Pays,Notes,Latitude,Longitude")] Adresse adresse)
        {
            if (id != adresse.AdresseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.Modifier(adresse);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_repo.Existe(adresse.AdresseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(adresse);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adresse = await _repo.LireAsync(id.Value);
            if (adresse == null)
            {
                return NotFound();
            }

            return View(adresse);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adresse = await _repo.LireAsync(id);
            await _repo.Supprimer(adresse);
            return RedirectToAction(nameof(Index));
        }
    }
}

GestionEvenements/Controllers/Api/EvenementsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestionEvenements.Services.Dal;

namespace GestionEvenements.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class EvenementsController : ControllerBase
    {
        private readonly GevDbContext _context;

        public EvenementsController(GevDbContext context)
        {
            _context = context;
        }

        // POST: api/evenements/ca/idev/idad
        [HttpPost]
        [Route("ca/{idev}/{idad}")]
        public async Task<int> AssocierAdresse(string idev, string idad)
        {
            if (!int.TryParse(idev, out var ide) || !int.TryParse(idad, out var ida))
            {
                throw new ArgumentException($"Ids idEv={idev}, idAd{idad} invalides dans api/Evenements/ca !");
            }

            var repo = new RepoEvenements(_context);
            return await repo.AssocierAdresse(ide, ida);
        }
        // POST: api/evenements/inscription/idev/idpa
        [HttpPost]
        [Route("inscription/{idev}/{idpa}")]
        public async Task<int> Inscription(string idev, string idpa)
        {
            if (!int.TryParse(idev, out var ide) || !int.TryParse(idpa, out var ida))
            {
                throw new ArgumentException($"Ids idEv={idev}, idAd{idpa} invalides dans api/Evenements/ca !");
            }

            var repo = new RepoEvenements(_context);
            return await repo.Inscription(ide, ida);
        }

    }
}

GestionEvenements/Controllers/EvenementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestionEvenements.Services.App;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionEvenements.Services.Dal;
using Microsoft.AspNetCore.Authorization;
using Modele;
using X.PagedList;

namespace GestionEvenements.Controllers
{
    [Authorize]
    [TypeFilter(typeof(LogExceptionFilter))]
    public class EvenementsController : Controller
    {
        private readonly RepoEvenements _repo;

        public EvenementsController(RepoEvenements repo)
        {
            _repo = repo;
        }

        // GET: Evenement/Inscription/idParticipant
        public async Task<IActionResult> Inscription(int id, string texteRecherche)
        {
            var repoPa = new RepoParticipants(_repo.Context);
            var participant = await repoPa.LireAsync(id);
            if (participant == null)
            {
                return NotFound();
            }

            ViewBag.PaId = id;
            ViewBag.Participant = participant.ToString();
            if (string.IsNullOrEmpty(texteRecherche))
            {
                return View();
            }
            ViewBag.Filtre = texteRecherche.Trim();
            List<Evenement> evenements = _repo.Liste(ViewBag.Filtre);
            int n = evenements.Count;
            ViewBag.Resultat = n == 0 ? "Aucune correspondance" : $"{n} événements trouvés";
            return View(evenements);
        }

        [AllowAnonymous]
        public async Task<ViewResult> Index(string sensTri, int? page)
        {
            int nbrLignes = 3;
            if (string.IsNullOrEmpty(sensTri)) sensTri = "titre";
            ViewBag.SensTri = sensTri;
            ViewBag.TriTitre = sensTri == "titre" ? "titre_desc" : "titre";
            ViewBag.TriAnnee = sensTri == "annee" ? "annee_desc" : "annee";

            int numPage = (page ?? 1);
            return View(await _repo.EvenementsTries(sensTri).ToPagedListAsync(numPage, nbrLignes));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _repo.LireAsync(id.Value);
            if (evenement == null)
            {
                return NotFound();
            }

            return View(evenement);
        }

        public IActionResult Create()
        {
            ViewBag.TypeEvenementId = new SelectList(_repo.TypesEvenementAvecValeurVide, "TypeEvenementId", "Libelle");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EvenementId,TypeEvenementId,Annee,DateEvenement,Titre,Description,Url,AdresseId")] Evenement evenement)
        {
            if (ModelState.IsValid)
            {
                await _repo.Creer(evenement);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.TypeEvenementId = new SelectList(_repo.TypesEvenementAvecValeurVide, "TypeEvenementId", "Libelle");

            return View(evenement);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _repo.LireAsync(id.Value);
            if (evenement == null)
            {
                return NotFound();
            }
            ViewBag.TypeEvenementId = new SelectList(_repo.TypesEvenementAvecValeurVide, "TypeEvenementId", "Libelle");
            return View(evenement);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EvenementId,TypeEvenementId,Annee,DateEvenement,Titre,Description,Url,AdresseId")] Evenement evenement)
        {
            if (id != evenement.EvenementId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.Modifier(evenement);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_repo.Existe(evenement.EvenementId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.TypeEvenementId = new SelectList(_repo.TypesEvenementAvecValeurVide, "TypeEvenementId", "Libelle");
            return View(evenement);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _repo.LireAsync(id.Value);
            if (evenement == null)
            {
                return NotFound();
            }

            return View(evenement);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evenement = await _repo.LireAsync(id);
            await _repo.Supprimer(evenement);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [ActionName("ra")]
        public async Task<IActionResult> RetirerAdresse(int id)
        {
            var evenement = await _repo.LireAsync(id);
            if (evenement == null)
            {
                return NotFound();
            }

            await _repo.RetirerAdresse(id);
            return RedirectToAction(nameof(Details), new { id = id });
        }
    }
}

GestionEvenements/Controllers/ParticipantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestionEvenements.Services.Dal;
using Microsoft.AspNetCore.Authorization;
using Modele;

namespace GestionEvenements.Controllers
{
    [Authorize]
    public class ParticipantsController : Controller
    {
        private readonly RepoParticipants _repo;

        public ParticipantsController(RepoParticipants repo)
        {
            _repo = repo;
        }

        // GET: Participants
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            // PN System.Linq.Async
            return View(await _repo.Liste().ToListAsync());
        }

        // GET: Participants/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _repo.LireAsync(id.Value);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participants/Create
        public IActionResult Create()
        {
            return View();
        }

     [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ParticipantId,Civilite,Nom,Prenom,AnneeNaissance,AnneeDeces,LieuNaissance,Activites,Url")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                await _repo.Creer(participant);
                return RedirectToAction(nameof(Index));
            }
            return View(participant);
        }

        // GET: Participants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _repo.LireAsync(id.Value);
            if (participant == null)
            {
                return NotFound();
            }
            return View(participant);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ParticipantId,Civilite,Nom,Prenom,AnneeNaissance,AnneeDeces,LieuNaissance,Activites,Url")] Participant participant)
        {
            if (id != participant.ParticipantId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.Modifier(participant);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_repo.Existe(participant.ParticipantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(participant);
        }

        // GET: Participants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _repo.LireAsync(id.Value);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _repo.LireAsync(id);
            await _repo.Supprimer(participant);
            return RedirectToAction(nameof(Index));
        }

    }
}

GestionEvenements/Views/Evenements/Create.cshtml
@model Modele.Evenement

@{
    ViewData["Title"] = "Nouvelle fiche";
}

<h1>Evénement</h1>

<h4>Création</h4>
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="TypeEvenementId" class="control-label"></label>
                <select asp-for="TypeEvenementId" class="form-control" asp-items="ViewBag.TypeEvenementId"></select>
                <span asp-validation-for="TypeEvenementId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Annee" class="control-label"></label>
                <input asp-for="Annee" class="form-control" />
                <span asp-validation-for="Annee" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEvenement" class="control-label"></label>
                <input asp-for="DateEvenement" class="form-control" />
                <span asp-validation-for="DateEvenement" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control" ></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Url" class="control-label"></label>
        <input asp-for="Url" class="form-control" />
        <span asp-validation-for="Url" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Enregistrer" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionEvenements/Views/Evenements/Delete.cshtml
@model Modele.Evenement

@{
    ViewData["Title"] = "Delete";
}

<h1>Confirmation de suppression de l'événement</h1>

<h3>Etes-vous sûr ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TypeEvenement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeEvenement.TypeEvenementId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Annee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Annee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEvenement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEvenement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse.AdresseId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EvenementId" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Liste</a>
    </form>
</div>

GestionEvenements/Views/Evenements/Details.cshtml
@model Modele.Evenement

@{
    ViewData["Title"] = "Details";
}

<h1>Evenement</h1>

<div>
    <h4>Fiche</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeEvenementId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeEvenement.Libelle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Titre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Annee)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Annee)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateEvenement)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateEvenement)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class="col-sm-10">
            <a href="@Html.DisplayFor(model => model.Url)" target="_blank">Lien</a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EvenementId">Modifier</a> |
    <a asp-action="Index">Liste</a>
</div>

<hr />
<div>
    <h3>Adresse</h3>
    @if (Model.AdresseId.HasValue)
    {
        <p>@Model.Adresse.Titre</p>
        <p>@Model.Adresse.Rue @Model.Adresse.CodePostal @Model.Adresse.Ville</p>
        <p>@Model.Adresse.Region @Model.Adresse.Pays</p>
        <p>@Model.Adresse.Notes</p>
        <div>
            <a asp-action="ra" asp-controller="Evenements"  asp-route-id="@Model.EvenementId">Retirer l'adresse</a>
        </div>
    }
    else
    {
        <div>
            <a asp-action="Create" asp-controller="Adresses" asp-route-id="@Model.EvenementId">Ajouter une adresse</a>
        </div>
    }
</div>

<hr />
<h4 style="margin-top:20px">Participations</h4>

<table class="table">
    <thead>
    <tr>
        <th>
            Civilité
        </th>
        <th>
            Nom
        </th>
        <th>
            Activités
        </th>

        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Participations)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Participant.Civilite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Participant.Prenom)&nbsp;
                @Html.DisplayFor(modelItem => item.Participant.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Participant.Activites)
            </td>
            <td>
                <a asp-controller="Participants" asp-action="Details" asp-route-id="@item.ParticipantId">Fiche</a>
            </td>
        </tr>
    }
    </tbody>
</table>


GestionEvenements/Views/Evenements/Edit.cshtml
@model Modele.Evenement

@{
    ViewData["Title"] = "Edit";
}
<h1>Evenement</h1>
<h4>Mise à jour</h4>
<hr />
<form asp-action="Edit">
    <div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="EvenementId" />
        <input type="hidden" asp-for="AdresseId" />
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="TypeEvenementId" class="control-label"></label>
                <select asp-for="TypeEvenementId" class="form-control" asp-items="ViewBag.TypeEvenementId"></select>
                <span asp-validation-for="TypeEvenementId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Annee" class="control-label"></label>
                <input asp-for="Annee" class="form-control" />
                <span asp-validation-for="Annee" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateEvenement" class="control-label"></label>
                <input asp-for="DateEvenement" class="form-control" />
                <span asp-validation-for="DateEvenement" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Url" class="control-label"></label>
        <input asp-for="Url" class="form-control" />
        <span asp-validation-for="Url" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Enregistrer" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionEvenements/Views/Evenements/Index.cshtml
@*@model IEnumerable<Modele.Evenement>*@
@model X.PagedList.IPagedList<Modele.Evenement>
@using X.PagedList.Mvc.Core;
@using X.PagedList
@using X.PagedList.Mvc.Bootstrap4.Core
@{
    ViewData["Title"] = "Evénements";
}

<h1>Evénements</h1>
<p>
    <a asp-action="Create">Nouvelle fiche</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Titre", "Index", new { sensTri = ViewBag.TriTitre })
            </th>
            <th>
                @Html.ActionLink("Année", "Index", new { sensTri = ViewBag.TriAnnee })
            </th>
            <th>
                Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td style="width:500px">
                    @Html.DisplayFor(modelItem => item.Titre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Annee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateEvenement)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.EvenementId">Fiche</a> |
                    <a asp-action="Edit" asp-route-id="@item.EvenementId">Modifier</a> |
                    <a asp-action="Delete" asp-route-id="@item.EvenementId">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />

@*IPagedList
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@

@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, sensTri = ViewBag.SensTri }), Bootstrap4PagedListRenderOptions.ClassicPlusFirstAndLast)

GestionEvenements/Views/Evenements/Inscription.cshtml
@model IEnumerable<Modele.Evenement>

@{
    ViewData["Title"] = "Inscription à un événement";
}

<h1>Inscription à un événement</h1>
<p>Pour @ViewBag.Participant</p>
<hr />
<form asp-controller="Evenements" asp-action="Inscription" method="get">
    <div class="row">
        <div class="col-2">
            <label class="control-label">Recherche</label>
        </div>
        <div class="col-5">
            <input name="TexteRecherche" type="text" value="@ViewBag.Filtre" />
        </div>
        <div class="col-2">
            <input type="submit" value="Recherche" />
        </div>
        <div>
            <p>@ViewBag.Resultat</p>
        </div>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Titre
            </th>
            <th>
                Année
            </th>
            <th>
                Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model != null)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Titre)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Annee)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateEvenement)
                        </td>
                        <td>
                            <input type="button" value="Inscription" data-idev="@item.EvenementId" data-idpa="@ViewBag.PaId"  />
                        </td>
                    </tr>
                }
            }
        }
    </tbody>
</table>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/inscription.js"></script>
}